#!/bin/sh
# this script is specific to ministry hacks

<% if configuration[:server_only] == "c4c" %>
# clean up production
cd /var/www/<%= configuration[:application] %>.<%= configuration[:domain] %>/current
sudo -u <%= configuration[:user] %> rake db:sessions:clear
sudo -u <%= configuration[:user] %> rake tmp:cache:clear

# clone production to staging
cd <%= configuration[:common] %>
sudo -u deploy rake <%= configuration[:application] %>:klone:<%= configuration[:server_only]%>:dev

# dump each site's stage
cd <%= configuration[:common] %>
sudo -u <%= configuration[:user] %> rake <%= configuration[:application] %>:dump:<%= configuration[:server_only] %>:prod
sudo -u <%= configuration[:user] %> rake <%= configuration[:application] %>:dump:<%= configuration[:server_only] %>:dev
sudo -u <%= configuration[:user] %> rake <%= configuration[:application] %>:dump:<%= configuration[:server_only] %>:staging
<% elsif configuration[:server_only] == "c4c2" %>
# pull production db
cd <%= configuration[:common] %>
sudo -u deploy cap c4c/prod pull:pulse sensitive=true force=true user=deploy 

# clone production to staging
cd <%= configuration[:common] %>
sudo -u deploy rake <%= configuration[:application] %>:klone:c4c:staging
<% end %>
